const OpenAI = require('openai');

const UA = 'Mozilla/5.0 (compatible; TrendProductEngine/0.7)';
const TIMEOUT_MS = 4500;

function clean(v = '') { return String(v).replace(/<!\[CDATA\[/g, '').replace(/\]\]>/g, '').replace(/<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, ' ').trim(); }
function arr(v) { return Array.isArray(v) ? v : (v == null || v === '' ? [] : [v]); }
function text(v, fallback = '') { if (typeof v === 'string') return v.trim() || fallback; if (typeof v === 'number') return String(v); if (v && typeof v === 'object') return v.detail || v.text || fallback; return fallback; }
function rssItems(xml, limit = 10) { const out = []; const matches = String(xml).match(/<item[\s\S]*?<\/item>/gi) || []; for (const block of matches.slice(0, limit)) { const title = clean((block.match(/<title>([\s\S]*?)<\/title>/i) || [, ''])[1]); const link = clean((block.match(/<link>([\s\S]*?)<\/link>/i) || [, ''])[1]); const pubDate = clean((block.match(/<pubDate>([\s\S]*?)<\/pubDate>/i) || [, ''])[1]); if (title) out.push({ title, link, pubDate }); } return out; }
async function fetchText(url, headers = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), TIMEOUT_MS); try { const r = await fetch(url, { signal: controller.signal, headers: { 'User-Agent': UA, ...headers } }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return await r.text(); } finally { clearTimeout(timer); } }
async function safe(fn) { try { return await fn(); } catch (e) { console.error(e?.message || e); return []; } }
async function autocomplete(prefix) { return safe(async () => { const raw = await fetchText(`https://suggestqueries.google.com/complete/search?client=firefox&hl=en-GB&q=${encodeURIComponent(prefix)}`, { Accept: 'application/json,text/plain,*/*', 'Accept-Language': 'en-GB,en;q=0.9' }); const data = JSON.parse(raw); return Array.isArray(data?.[1]) ? data[1].map(x => typeof x === 'string' ? x : x?.[0]).filter(Boolean).slice(0, 10) : []; }); }
async function searchIntentDiscovery() { const bases = ['how to','how do I','how can I','help with','alternative to','replacement for','best way to','problem with','why does','is there a way to','what can I use instead of']; const variants = ['', ' a', ' c', ' m', ' s', ' t']; const jobs = bases.flatMap(base => variants.map(v => base + v)); const batches = await Promise.all(jobs.map(async prefix => ({ prefix, suggestions: await autocomplete(prefix) }))); const rows = []; for (const b of batches) for (const query of b.suggestions) rows.push({ query, prefix: b.prefix, source: 'Google Autocomplete', signalType: 'search-intent' }); return Array.from(new Map(rows.map(x => [x.query.toLowerCase(), x])).values()).filter(x => x.query.length > 12).slice(0, 180); }
async function googleTrends() { return safe(async () => rssItems(await fetchText('https://trends.google.com/trending/rss?geo=GB'), 30).map(x => ({ ...x, source: 'Google Trends', signalType: 'trending search' }))); }
async function googleNews(query, limit = 8) { return safe(async () => rssItems(await fetchText(`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-GB&gl=GB&ceid=GB:en`), limit).map(x => ({ ...x, source: 'Google News', signalType: 'context' }))); }
async function redditSearch(query) { return safe(async () => { const r = await fetch(`https://www.reddit.com/search.json?q=${encodeURIComponent(query)}&sort=relevance&limit=12`, { signal: AbortSignal.timeout(TIMEOUT_MS), headers: { 'User-Agent': UA, Accept: 'application/json' } }); if (!r.ok) return []; const d = await r.json(); return (d?.data?.children || []).map(x => ({ title: x?.data?.title || '', link: x?.data?.permalink ? `https://www.reddit.com${x.data.permalink}` : '', pubDate: x?.data?.created_utc ? new Date(x.data.created_utc * 1000).toISOString() : '', source: 'Reddit', signalType: 'customer discussion' })).filter(x => x.title); }); }
async function youtubeSearch(query, limit = 6) { return safe(async () => { const html = await fetchText(`https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`, { 'Accept-Language': 'en-GB,en;q=0.9' }); const marker = 'var ytInitialData = ', start = html.indexOf(marker); if (start < 0) return []; const jsonStart = start + marker.length, end = html.indexOf(';var ytInitialPlayerResponse', jsonStart), scriptEnd = html.indexOf('</script>', jsonStart); const raw = html.slice(jsonStart, end > jsonStart ? end : scriptEnd).trim().replace(/;$/, ''); const data = JSON.parse(raw), results = []; function walk(node) { if (!node || results.length >= limit) return; if (Array.isArray(node)) { for (const x of node) walk(x); return; } if (typeof node !== 'object') return; const r = node.videoRenderer; if (r?.videoId && r?.title?.runs?.length) results.push({ title: r.title.runs.map(x => x.text || '').join('').trim(), link: `https://www.youtube.com/watch?v=${r.videoId}`, channel: r.ownerText?.runs?.map(x => x.text || '').join('').trim() || '', published: r.publishedTimeText?.simpleText || '', views: r.viewCountText?.simpleText || '', query, source: 'YouTube', signalType: 'content/search signal' }); for (const v of Object.values(node)) walk(v); } walk(data); return results.filter(x => x.title); }); }
async function youtubeDiscovery(queries) { const selected = queries.filter(x => x.query.length > 15).slice(0, 12); return (await Promise.all(selected.map(x => youtubeSearch(x.query)))).flat(); }
function normalizeEvidence(v, fallback = 'AI analysis') { return arr(v).map(x => typeof x === 'string' ? { source: fallback, detail: x, url: '' } : { source: text(x?.source, fallback), detail: text(x?.detail || x?.text, ''), url: text(x?.url || x?.link, '') }).filter(x => x.detail); }
function normalizeSources(v) { return arr(v).map(x => typeof x === 'string' ? x : x?.url || x?.link || '').filter(x => /^https?:\/\//i.test(x)).slice(0, 12); }
function normalizeOpportunity(x, i) { const evidence = normalizeEvidence(x?.evidence), complaints = normalizeEvidence(x?.complaintsEvidence); const states = new Set(['Observed','Inferred','Unknown']); const evidenceState = states.has(x?.evidenceState) ? x.evidenceState : (evidence.length >= 3 ? 'Observed' : 'Unknown'); const statuses = new Set(['Validated','Promising lead','Needs validation','Killed']); const validationStatus = statuses.has(x?.validationStatus) ? x.validationStatus : 'Needs validation'; return { category:text(x?.category,'Emerging problem'), title:text(x?.title,`Potential opportunity ${i+1}`), problem:text(x?.problem,'Specific problem needs further definition.'), trend:text(x?.trend,'Live search-intent signals identified; no unsupported growth claim.'), evidenceState, validationStatus, confidence:Math.max(1,Math.min(10,Number.parseInt(x?.confidence,10)||1)), evidence:evidence.slice(0,8), products:text(x?.products,'No sufficiently specific existing solutions identified from supplied evidence.'), complaintsEvidence:complaints.slice(0,7), gap:text(x?.gap,'Product gap not established.'), unproven:text(x?.unproven,'Search volume, willingness to pay and the product gap still require validation.'), audience:text(x?.audience,'Audience needs further investigation.'), ads:text(x?.ads,'Channel hypothesis only; validate.'), sell:text(x?.sell,'Sales-channel hypothesis only; validate.'), next:text(x?.next,'Validate the problem, existing alternatives and willingness to pay before sourcing.'), sources:normalizeSources(x?.sources) }; }
function coverage(searchIntent, youtube, trends, reddit, news, model) { return { searchIntent, youtube, youtubeEnabled:true, googleTrends:trends, googleNews:news, reddit, model, version:'V0.7' }; }

module.exports = async (req, res) => {
  if (req.method !== 'GET') return res.status(405).json({ message:'GET only' });
  const model = process.env.OPENAI_MODEL || 'gpt-4o-mini';
  if (!process.env.OPENAI_API_KEY) return res.status(200).json({ version:'V0.7', opportunities:[], discoveries:[], investigations:[], validatedOpportunities:[], message:'OPENAI_API_KEY is not available to this deployment. Add it to Production and redeploy.' });
  try {
    const [searchQueries, trends] = await Promise.all([searchIntentDiscovery(), googleTrends()]);
    if (searchQueries.length < 30) return res.status(200).json({ version:'V0.7', opportunities:[], discoveries:[], investigations:[], validatedOpportunities:[], scannedAt:new Date().toISOString(), sourceCoverage:coverage(searchQueries.length,0,trends.length,0,0,model), message:'Search discovery returned too little data for a reliable scan.' });
    const youtube = await youtubeDiscovery(searchQueries);
    const client = new OpenAI({ apiKey:process.env.OPENAI_API_KEY });

    const discoveryPrompt = `You are Stage 1 of a commercial product research engine. Discover recurring HUMAN PROBLEMS from live search behaviour. Do not begin with product categories or product ideas. Autocomplete means a query exists, not that demand, growth or willingness to pay is proven. Never invent metrics. Return ONLY JSON: {"discoveries":[{"theme":"short problem theme","problem":"specific human problem","evidenceState":"Observed|Inferred|Unknown","searchEvidence":[{"query":"exact supplied query","prefix":"exact supplied prefix"}],"contentEvidence":[{"title":"exact supplied title","url":"exact supplied URL","views":"exact supplied value or blank"}],"next":"what evidence should be gathered next"}]}. Use only supplied evidence. Require at least 2 distinct supplied search queries per discovery. Reject recipes, games, celebrity/news, generic learning and generic AI/app tutorials.`;
    const r1 = await client.chat.completions.create({ model, temperature:0, response_format:{type:'json_object'}, messages:[{role:'system',content:'Evidence-led discovery. Never manufacture evidence.'},{role:'user',content:`${discoveryPrompt}\n\nDATA:\n${JSON.stringify({searchQueries,youtube,trends}).slice(0,70000)}`}] });
    const discoveries = arr(JSON.parse(r1.choices?.[0]?.message?.content || '{}')?.discoveries).filter(x => Array.isArray(x?.searchEvidence) && x.searchEvidence.length >= 2).slice(0,10);
    if (!discoveries.length) return res.status(200).json({ version:'V0.7', opportunities:[], discoveries:[], investigations:[], validatedOpportunities:[], scannedAt:new Date().toISOString(), sourceCoverage:coverage(searchQueries.length,youtube.length,trends.length,0,0,model), message:'Search behaviour found, but no recurring problem passed the discovery threshold.' });

    const investigations = await Promise.all(discoveries.map(async discovery => { const q = text(discovery.problem || discovery.theme); const terms = [q,`${q} problem`,`${q} review`,`${q} frustrating`]; const batches = await Promise.all(terms.map(async term => { const [reddit,news] = await Promise.all([redditSearch(term),googleNews(`"${term}"`,6)]); return {reddit,news}; })); return { discovery, reddit:batches.flatMap(x=>x.reddit).slice(0,25), news:batches.flatMap(x=>x.news).slice(0,20) }; }));
    const reddit = investigations.flatMap(x=>x.reddit), news = investigations.flatMap(x=>x.news);

    const auditPrompt = `You are Stage 3 of an evidence-led product research engine. Convert discoveries into potential opportunities ONLY when evidence supports them. Search/autocomplete is behavioural evidence only. YouTube titles are content signals, not complaints. Google News is context unless its supplied title is clearly a review/complaint. Reddit/customer discussion can establish pain but does not prove market size or willingness to pay. Never invent brands, prices, review counts, volume, growth, market size, URLs or sentiment. Separate Observed facts from Inferred hypotheses and Unknowns. A Promising lead requires multiple independent search/content signals plus at least one genuine customer/problem signal. Validated requires the supplied evidence to support the problem, a concrete product gap and repeated customer pain. Otherwise use Needs validation. Use Killed where evidence contradicts or is too weak to justify further investigation. Do not force results. Return ONLY JSON: {"opportunities":[{"category":"descriptive problem category","title":"specific potential product opportunity","problem":"specific problem","trend":"what evidence actually shows","evidenceState":"Observed|Inferred|Unknown","validationStatus":"Validated|Promising lead|Needs validation|Killed","confidence":1,"evidence":[{"source":"Google Autocomplete|YouTube|Google Trends|Reddit|Google News","detail":"fact supported by supplied data","url":"actual supplied URL or blank"}],"products":"Only evidenced existing solutions","complaintsEvidence":[{"source":"Reddit|Google News","detail":"actual customer/problem evidence","url":"actual supplied URL"}],"gap":"evidence-supported gap or not established","unproven":"unknowns","audience":"evidence-supported audience","ads":"hypothesis only","sell":"hypothesis only","next":"next validation action","sources":["actual supplied URLs"]}]}.`;
    const r2 = await client.chat.completions.create({ model, temperature:0, response_format:{type:'json_object'}, messages:[{role:'system',content:'Strict commercial research auditor. Never manufacture evidence.'},{role:'user',content:`${auditPrompt}\n\nRESEARCH DATA:\n${JSON.stringify({discoveries,investigations,trends}).slice(0,85000)}`}] });
    const rawOpps = arr(JSON.parse(r2.choices?.[0]?.message?.content || '{}')?.opportunities).map(normalizeOpportunity);
    const opportunities = rawOpps.filter(x => x.validationStatus !== 'Killed' && x.evidence.length >= 3 && x.complaintsEvidence.length >= 1).slice(0,8);
    const validatedOpportunities = opportunities.filter(x => x.validationStatus === 'Validated');
    const promoted = opportunities.filter(x => x.validationStatus === 'Promising lead' || x.validationStatus === 'Validated');
    return res.status(200).json({ version:'V0.7', scannedAt:new Date().toISOString(), discoveries, investigations, validatedOpportunities, opportunities:promoted, sourceCoverage:coverage(searchQueries.length,youtube.length,trends.length,reddit.length,news.length,model), message:promoted.length ? undefined : 'No opportunity has enough independent evidence to be promoted yet.' });
  } catch (e) {
    console.error('V0.7 scan failed:',e?.message || e);
    return res.status(200).json({ version:'V0.7', opportunities:[], discoveries:[], investigations:[], validatedOpportunities:[], scannedAt:new Date().toISOString(), message:'The V0.7 scan could not complete. Check the deployment logs and source API availability.' });
  }
};
